-- Migration to add ProductCategories table and remove CategoryId from Products
-- This migration should be run on the production database

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260129_AddProductCategoriesTable') THEN
    
    -- Step 1: Create ProductCategories table
    CREATE TABLE "ProductCategories" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "ProductId" integer NOT NULL,
        "CategoryId" integer NOT NULL,
        "CreatedAt" text NOT NULL,
        "UpdatedAt" text,
        "DeletedAt" text,
        "CreatedBy" integer,
        "UpdatedBy" integer,
        "DeletedBy" integer,
        "IsDeleted" boolean NOT NULL DEFAULT FALSE,
        CONSTRAINT "PK_ProductCategories" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_ProductCategories_Products_ProductId" FOREIGN KEY ("ProductId") REFERENCES "Products" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_ProductCategories_Categories_CategoryId" FOREIGN KEY ("CategoryId") REFERENCES "Categories" ("Id") ON DELETE CASCADE
    );
    
    -- Step 2: Create indexes for ProductCategories
    CREATE INDEX "IX_ProductCategories_ProductId" ON "ProductCategories" ("ProductId");
    CREATE INDEX "IX_ProductCategories_CategoryId" ON "ProductCategories" ("CategoryId");
    
    -- Step 3: Migrate existing data from Products.CategoryId to ProductCategories
    INSERT INTO "ProductCategories" ("ProductId", "CategoryId", "CreatedAt", "IsDeleted")
    SELECT 
        "Id" as "ProductId",
        "CategoryId",
        COALESCE("CreatedAt", NOW()::text) as "CreatedAt",
        FALSE as "IsDeleted"
    FROM "Products"
    WHERE "CategoryId" IS NOT NULL AND "DeletedAt" IS NULL;
    
    -- Step 4: Drop the foreign key constraint on Products.CategoryId
    ALTER TABLE "Products" DROP CONSTRAINT IF EXISTS "FK_Products_Categories_CategoryId";
    
    -- Step 5: Drop the index on Products.CategoryId
    DROP INDEX IF EXISTS "IX_Products_CategoryId";
    
    -- Step 6: Drop the CategoryId column from Products
    ALTER TABLE "Products" DROP COLUMN IF EXISTS "CategoryId";
    
    -- Step 7: Record migration
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260129_AddProductCategoriesTable', '9.0.10');
    
    END IF;
END $EF$;
