CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251107051528_InitialMigration') THEN
    CREATE TABLE "Admins" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "FirstName" text NOT NULL,
        "LastName" text NOT NULL,
        "Username" text NOT NULL,
        "Phone" text NOT NULL,
        "Email" text NOT NULL,
        "PasswordHash" text NOT NULL,
        "Role" text NOT NULL,
        "Permissions" text,
        "IsActive" boolean NOT NULL,
        "LastLoginAt" timestamp with time zone,
        "CreatedAt" text NOT NULL,
        "UpdatedAt" text,
        "DeletedAt" text,
        "CreatedBy" integer,
        "UpdatedBy" integer,
        "DeletedBy" integer,
        CONSTRAINT "PK_Admins" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251107051528_InitialMigration') THEN
    CREATE TABLE "Categories" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" text NOT NULL,
        "Description" text,
        "ParentId" integer,
        "IsActive" boolean NOT NULL,
        "ImageUrl" text,
        "DisplayOrder" integer NOT NULL,
        "CreatedAt" text NOT NULL,
        "UpdatedAt" text,
        "DeletedAt" text,
        "CreatedBy" integer,
        "UpdatedBy" integer,
        "DeletedBy" integer,
        CONSTRAINT "PK_Categories" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Categories_Categories_ParentId" FOREIGN KEY ("ParentId") REFERENCES "Categories" ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251107051528_InitialMigration') THEN
    CREATE TABLE "Contents" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "ContentType" integer NOT NULL,
        "Title" text NOT NULL,
        "Description" text,
        "ContentUrl" text,
        "ContentData" text,
        "TargetAudience" text NOT NULL,
        "IsActive" boolean NOT NULL,
        "DisplayOrder" integer NOT NULL,
        "ValidFrom" timestamp with time zone NOT NULL,
        "ValidUntil" timestamp with time zone,
        "ViewCount" integer NOT NULL,
        "ClickCount" integer NOT NULL,
        "Tags" text,
        "SeoTitle" text,
        "SeoDescription" text,
        "SeoKeywords" text,
        "Language" text NOT NULL,
        "Author" text,
        "ThumbnailUrl" text,
        "VideoDuration" integer,
        "FileSize" bigint,
        "MimeType" text,
        "CreatedAt" text NOT NULL,
        "UpdatedAt" text,
        "DeletedAt" text,
        "CreatedBy" integer,
        "UpdatedBy" integer,
        "DeletedBy" integer,
        CONSTRAINT "PK_Contents" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251107051528_InitialMigration') THEN
    CREATE TABLE "Customers" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "FirstName" text NOT NULL,
        "LastName" text NOT NULL,
        "Phone" text NOT NULL,
        "Email" text,
        "PasswordHash" text NOT NULL,
        "Address" text,
        "FcmToken" text,
        "CashbackBalance" numeric NOT NULL,
        "IsActive" boolean NOT NULL,
        "CreatedAt" text NOT NULL,
        "UpdatedAt" text,
        "DeletedAt" text,
        "CreatedBy" integer,
        "UpdatedBy" integer,
        "DeletedBy" integer,
        CONSTRAINT "PK_Customers" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251107051528_InitialMigration') THEN
    CREATE TABLE "DailySalesSummaries" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "SaleDate" date NOT NULL,
        "TotalOrders" integer NOT NULL,
        "TotalRevenue" numeric NOT NULL,
        "TotalDiscount" numeric NOT NULL,
        "CashbackUsed" numeric NOT NULL,
        "CashbackGiven" numeric NOT NULL,
        "OnlineOrders" integer NOT NULL,
        "OfflineOrders" integer NOT NULL,
        "CancelledOrders" integer NOT NULL,
        "DeliveredOrders" integer NOT NULL,
        "NewCustomers" integer NOT NULL,
        "ReturningCustomers" integer NOT NULL,
        "TotalItemsSold" integer NOT NULL,
        "AverageOrderValue" numeric NOT NULL,
        "CashPayments" numeric NOT NULL,
        "CardPayments" numeric NOT NULL,
        "TopSellingProductId" integer,
        "TopSellingProductQuantity" integer NOT NULL,
        "TopSellerId" integer,
        "TopSellerRevenue" numeric NOT NULL,
        "TopCustomerId" integer,
        "TopCustomerSpending" numeric NOT NULL,
        "AdditionalMetrics" text,
        "CreatedAt" text NOT NULL,
        "UpdatedAt" text,
        "DeletedAt" text,
        CONSTRAINT "PK_DailySalesSummaries" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251107051528_InitialMigration') THEN
    CREATE TABLE "DeliveryPartners" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" text NOT NULL,
        "Phone" text,
        "Email" text,
        "DeliveryType" text NOT NULL,
        "PricePerDelivery" numeric NOT NULL,
        "EstimatedDays" integer NOT NULL,
        "MaxWeight" numeric,
        "ServiceAreas" text,
        "IsActive" boolean NOT NULL,
        "DisplayOrder" integer NOT NULL,
        "ApiUrl" text,
        "ApiKey" text,
        "Notes" text,
        "CreatedAt" text NOT NULL,
        "UpdatedAt" text,
        "DeletedAt" text,
        "CreatedBy" integer,
        "UpdatedBy" integer,
        "DeletedBy" integer,
        CONSTRAINT "PK_DeliveryPartners" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251107051528_InitialMigration') THEN
    CREATE TABLE "DiscountReasons" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" text NOT NULL,
        "Description" text,
        "IsActive" boolean NOT NULL,
        "MaxDiscountPercentage" numeric,
        "MaxDiscountAmount" numeric,
        "IsSellerOnly" boolean NOT NULL,
        "DisplayOrder" integer NOT NULL,
        "CreatedAt" text NOT NULL,
        "UpdatedAt" text,
        "DeletedAt" text,
        "CreatedBy" integer,
        "UpdatedBy" integer,
        "DeletedBy" integer,
        CONSTRAINT "PK_DiscountReasons" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251107051528_InitialMigration') THEN
    CREATE TABLE "Sellers" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "FirstName" text NOT NULL,
        "LastName" text NOT NULL,
        "Phone" text NOT NULL,
        "PasswordHash" text NOT NULL,
        "Role" text NOT NULL,
        "IsActive" boolean NOT NULL,
        "CreatedAt" text NOT NULL,
        "UpdatedAt" text,
        "DeletedAt" text,
        "CreatedBy" integer,
        "UpdatedBy" integer,
        "DeletedBy" integer,
        CONSTRAINT "PK_Sellers" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251107051528_InitialMigration') THEN
    CREATE TABLE "SystemSettings" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "SettingKey" text NOT NULL,
        "SettingValue" text NOT NULL,
        "Description" text,
        "DataType" text NOT NULL,
        "IsEditable" boolean NOT NULL,
        "Category" text,
        "DefaultValue" text,
        "ValidationPattern" text,
        "ValidationMessage" text,
        "MinValue" numeric,
        "MaxValue" numeric,
        "AllowedValues" text,
        "DisplayOrder" integer NOT NULL,
        "IsSecure" boolean NOT NULL,
        "RequiresRestart" boolean NOT NULL,
        "CreatedAt" text NOT NULL,
        "UpdatedAt" text,
        "DeletedAt" text,
        "CreatedBy" integer,
        "UpdatedBy" integer,
        "DeletedBy" integer,
        CONSTRAINT "PK_SystemSettings" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251107051528_InitialMigration') THEN
    CREATE TABLE "Products" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" text NOT NULL,
        "SearchText" text,
        "Description" text,
        "QrCode" text NOT NULL,
        "Price" numeric NOT NULL,
        "StockQuantity" integer NOT NULL,
        "CategoryId" integer NOT NULL,
        "Status" integer NOT NULL,
        "ImageUrl" text,
        "IsActive" boolean NOT NULL,
        "MinStockLevel" integer NOT NULL,
        "Weight" numeric,
        "Dimensions" text,
        "Manufacturer" text,
        "DisplayOrder" integer NOT NULL,
        "CreatedAt" text NOT NULL,
        "UpdatedAt" text,
        "DeletedAt" text,
        "CreatedBy" integer,
        "UpdatedBy" integer,
        "DeletedBy" integer,
        CONSTRAINT "PK_Products" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Products_Categories_CategoryId" FOREIGN KEY ("CategoryId") REFERENCES "Categories" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251107051528_InitialMigration') THEN
    CREATE TABLE "SupportChats" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "CreatedBy" integer NOT NULL,
        "DeletedBy" integer NOT NULL,
        "Resolution" text NOT NULL,
        "CustomerId" integer NOT NULL,
        "StartedAt" timestamp with time zone,
        "OrderId" integer,
        "UpdatedBy" integer,
        "AdminId" integer,
        "Subject" text,
        "Status" integer NOT NULL,
        "Priority" text,
        "Category" text,
        "CloseReason" text,
        "CustomerRating" integer,
        "CustomerFeedback" text,
        "FirstResponseAt" text,
        "LastActivityAt" text,
        "AutoCloseAt" text,
        "Tags" text,
        "CreatedAt" text NOT NULL,
        "UpdatedAt" text,
        "DeletedAt" text,
        CONSTRAINT "PK_SupportChats" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_SupportChats_Admins_AdminId" FOREIGN KEY ("AdminId") REFERENCES "Admins" ("Id"),
        CONSTRAINT "FK_SupportChats_Customers_CustomerId" FOREIGN KEY ("CustomerId") REFERENCES "Customers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251107051528_InitialMigration') THEN
    CREATE TABLE "Notifications" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "UserId" integer NOT NULL,
        "UserType" integer NOT NULL,
        "NotificationType" integer NOT NULL,
        "Title" text NOT NULL,
        "Message" text NOT NULL,
        "Data" text,
        "IsRead" boolean NOT NULL,
        "ReadAt" timestamp with time zone,
        "IsPushSent" boolean NOT NULL,
        "IsEmailSent" boolean NOT NULL,
        "IsSmsSent" boolean NOT NULL,
        "PushSentAt" timestamp with time zone,
        "EmailSentAt" timestamp with time zone,
        "SmsSentAt" timestamp with time zone,
        "Priority" text NOT NULL,
        "ExpiresAt" timestamp with time zone,
        "ActionUrl" text,
        "ActionText" text,
        "ImageUrl" text,
        "CustomerId" integer,
        "SellerId" integer,
        "AdminId" integer,
        "CreatedAt" text NOT NULL,
        "UpdatedAt" text,
        "DeletedAt" text,
        CONSTRAINT "PK_Notifications" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Notifications_Admins_AdminId" FOREIGN KEY ("AdminId") REFERENCES "Admins" ("Id"),
        CONSTRAINT "FK_Notifications_Customers_CustomerId" FOREIGN KEY ("CustomerId") REFERENCES "Customers" ("Id"),
        CONSTRAINT "FK_Notifications_Sellers_SellerId" FOREIGN KEY ("SellerId") REFERENCES "Sellers" ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251107051528_InitialMigration') THEN
    CREATE TABLE "Orders" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "OrderNumber" text NOT NULL,
        "CustomerId" integer NOT NULL,
        "SellerId" integer,
        "OrderDate" text NOT NULL,
        "Status" integer NOT NULL,
        "TotalPrice" numeric NOT NULL,
        "DiscountApplied" numeric NOT NULL,
        "CashbackUsed" numeric NOT NULL,
        "FinalPrice" numeric NOT NULL,
        "PaymentMethod" integer NOT NULL,
        "PaymentReference" text,
        "PaidAt" text,
        "DeliveryType" integer NOT NULL,
        "DeliveryAddress" text,
        "DeliveryFee" numeric NOT NULL,
        "CustomerNotes" text,
        "SellerNotes" text,
        "AdminNotes" text,
        "CreatedAt" text NOT NULL,
        "UpdatedAt" text,
        "DeletedAt" text,
        "CreatedBy" integer,
        "UpdatedBy" integer,
        "DeletedBy" integer,
        CONSTRAINT "PK_Orders" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Orders_Customers_CustomerId" FOREIGN KEY ("CustomerId") REFERENCES "Customers" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_Orders_Sellers_SellerId" FOREIGN KEY ("SellerId") REFERENCES "Sellers" ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251107051528_InitialMigration') THEN
    CREATE TABLE "CartItems" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "CustomerId" integer NOT NULL,
        "ProductId" integer NOT NULL,
        "Quantity" integer NOT NULL,
        "UnitPrice" numeric NOT NULL,
        "AddedAt" timestamp with time zone NOT NULL,
        "CreatedAt" text NOT NULL,
        "UpdatedAt" text,
        "DeletedAt" text,
        CONSTRAINT "PK_CartItems" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_CartItems_Customers_CustomerId" FOREIGN KEY ("CustomerId") REFERENCES "Customers" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_CartItems_Products_ProductId" FOREIGN KEY ("ProductId") REFERENCES "Products" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251107051528_InitialMigration') THEN
    CREATE TABLE "ProductLikes" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "CustomerId" integer NOT NULL,
        "ProductId" integer NOT NULL,
        "LikedAt" timestamp with time zone NOT NULL,
        "CreatedAt" text NOT NULL,
        "UpdatedAt" text,
        "DeletedAt" text,
        CONSTRAINT "PK_ProductLikes" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_ProductLikes_Customers_CustomerId" FOREIGN KEY ("CustomerId") REFERENCES "Customers" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_ProductLikes_Products_ProductId" FOREIGN KEY ("ProductId") REFERENCES "Products" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251107051528_InitialMigration') THEN
    CREATE TABLE "SupportMessages" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "DeletedBy" integer,
        "UpdatedBy" integer NOT NULL,
        "ChatId" integer NOT NULL,
        "SenderId" integer NOT NULL,
        "SenderType" integer NOT NULL,
        "AttachmentUrl" text,
        "Message" text NOT NULL,
        "MessageType" text NOT NULL,
        "FileUrl" text,
        "FileName" text,
        "FileSize" bigint,
        "IsRead" boolean NOT NULL,
        "ReadAt" timestamp with time zone,
        "IsDeleted" boolean NOT NULL,
        "IsEdited" boolean NOT NULL,
        "EditedAt" timestamp with time zone,
        "OriginalMessage" text,
        "ReplyToMessageId" integer,
        "IsInternal" boolean NOT NULL,
        "Metadata" text,
        "CreatedAt" text NOT NULL,
        "UpdatedAt" text,
        "DeletedAt" text,
        CONSTRAINT "PK_SupportMessages" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_SupportMessages_SupportChats_ChatId" FOREIGN KEY ("ChatId") REFERENCES "SupportChats" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_SupportMessages_SupportMessages_ReplyToMessageId" FOREIGN KEY ("ReplyToMessageId") REFERENCES "SupportMessages" ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251107051528_InitialMigration') THEN
    CREATE TABLE "CashbackTransactions" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "CustomerId" integer NOT NULL,
        "OrderId" integer,
        "Type" integer NOT NULL,
        "Amount" numeric NOT NULL,
        "RemainingAmount" numeric NOT NULL,
        "EarnedAt" text NOT NULL,
        "ExpiresAt" text NOT NULL,
        "UsedAt" text,
        "Description" text,
        "TransactionNumber" text NOT NULL,
        "CreatedAt" text NOT NULL,
        "UpdatedAt" text,
        "DeletedAt" text,
        CONSTRAINT "PK_CashbackTransactions" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_CashbackTransactions_Customers_CustomerId" FOREIGN KEY ("CustomerId") REFERENCES "Customers" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_CashbackTransactions_Orders_OrderId" FOREIGN KEY ("OrderId") REFERENCES "Orders" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251107051528_InitialMigration') THEN
    CREATE TABLE "OrderDeliveries" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "OrderId" integer NOT NULL,
        "DeliveryPartnerId" integer NOT NULL,
        "TrackingCode" text,
        "DeliveryStatus" integer NOT NULL,
        "DeliveryAddress" text NOT NULL,
        "DeliveryFee" numeric NOT NULL,
        "AssignedAt" timestamp with time zone NOT NULL,
        "PickedUpAt" timestamp with time zone,
        "DeliveredAt" timestamp with time zone,
        "FailedAt" timestamp with time zone,
        "FailureReason" text,
        "ReceiverName" text,
        "ReceiverPhone" text,
        "DeliveryPersonId" text,
        "Notes" text,
        "EstimatedDeliveryDate" timestamp with time zone,
        "AttemptCount" integer NOT NULL,
        "DeliveryLocation" text,
        "CreatedAt" text NOT NULL,
        "UpdatedAt" text,
        "DeletedAt" text,
        CONSTRAINT "PK_OrderDeliveries" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_OrderDeliveries_DeliveryPartners_DeliveryPartnerId" FOREIGN KEY ("DeliveryPartnerId") REFERENCES "DeliveryPartners" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_OrderDeliveries_Orders_OrderId" FOREIGN KEY ("OrderId") REFERENCES "Orders" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251107051528_InitialMigration') THEN
    CREATE TABLE "OrderDiscounts" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Amount" numeric NOT NULL,
        "AppliedBy" integer NOT NULL,
        "OrderId" integer NOT NULL,
        "DiscountReasonId" integer NOT NULL,
        "DiscountAmount" numeric NOT NULL,
        "AppliedBySellerId" integer,
        "Notes" text,
        "AppliedAt" timestamp with time zone NOT NULL,
        "CreatedAt" text NOT NULL,
        "UpdatedAt" text,
        "DeletedAt" text,
        CONSTRAINT "PK_OrderDiscounts" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_OrderDiscounts_DiscountReasons_DiscountReasonId" FOREIGN KEY ("DiscountReasonId") REFERENCES "DiscountReasons" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_OrderDiscounts_Orders_OrderId" FOREIGN KEY ("OrderId") REFERENCES "Orders" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_OrderDiscounts_Sellers_AppliedBySellerId" FOREIGN KEY ("AppliedBySellerId") REFERENCES "Sellers" ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251107051528_InitialMigration') THEN
    CREATE TABLE "OrderItems" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "OrderId" integer NOT NULL,
        "ProductId" integer NOT NULL,
        "ProductName" text NOT NULL,
        "Quantity" integer NOT NULL,
        "UnitPrice" numeric NOT NULL,
        "DiscountApplied" numeric NOT NULL,
        "CreatedAt" text NOT NULL,
        "UpdatedAt" text,
        "DeletedAt" text,
        CONSTRAINT "PK_OrderItems" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_OrderItems_Orders_OrderId" FOREIGN KEY ("OrderId") REFERENCES "Orders" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_OrderItems_Products_ProductId" FOREIGN KEY ("ProductId") REFERENCES "Products" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251107051528_InitialMigration') THEN
    CREATE INDEX "IX_CartItems_CustomerId" ON "CartItems" ("CustomerId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251107051528_InitialMigration') THEN
    CREATE INDEX "IX_CartItems_ProductId" ON "CartItems" ("ProductId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251107051528_InitialMigration') THEN
    CREATE INDEX "IX_CashbackTransactions_CustomerId" ON "CashbackTransactions" ("CustomerId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251107051528_InitialMigration') THEN
    CREATE INDEX "IX_CashbackTransactions_OrderId" ON "CashbackTransactions" ("OrderId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251107051528_InitialMigration') THEN
    CREATE INDEX "IX_Categories_ParentId" ON "Categories" ("ParentId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251107051528_InitialMigration') THEN
    CREATE INDEX "IX_Notifications_AdminId" ON "Notifications" ("AdminId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251107051528_InitialMigration') THEN
    CREATE INDEX "IX_Notifications_CustomerId" ON "Notifications" ("CustomerId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251107051528_InitialMigration') THEN
    CREATE INDEX "IX_Notifications_SellerId" ON "Notifications" ("SellerId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251107051528_InitialMigration') THEN
    CREATE INDEX "IX_OrderDeliveries_DeliveryPartnerId" ON "OrderDeliveries" ("DeliveryPartnerId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251107051528_InitialMigration') THEN
    CREATE UNIQUE INDEX "IX_OrderDeliveries_OrderId" ON "OrderDeliveries" ("OrderId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251107051528_InitialMigration') THEN
    CREATE INDEX "IX_OrderDiscounts_AppliedBySellerId" ON "OrderDiscounts" ("AppliedBySellerId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251107051528_InitialMigration') THEN
    CREATE INDEX "IX_OrderDiscounts_DiscountReasonId" ON "OrderDiscounts" ("DiscountReasonId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251107051528_InitialMigration') THEN
    CREATE INDEX "IX_OrderDiscounts_OrderId" ON "OrderDiscounts" ("OrderId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251107051528_InitialMigration') THEN
    CREATE INDEX "IX_OrderItems_OrderId" ON "OrderItems" ("OrderId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251107051528_InitialMigration') THEN
    CREATE INDEX "IX_OrderItems_ProductId" ON "OrderItems" ("ProductId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251107051528_InitialMigration') THEN
    CREATE INDEX "IX_Orders_CustomerId" ON "Orders" ("CustomerId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251107051528_InitialMigration') THEN
    CREATE INDEX "IX_Orders_SellerId" ON "Orders" ("SellerId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251107051528_InitialMigration') THEN
    CREATE INDEX "IX_ProductLikes_CustomerId" ON "ProductLikes" ("CustomerId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251107051528_InitialMigration') THEN
    CREATE INDEX "IX_ProductLikes_ProductId" ON "ProductLikes" ("ProductId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251107051528_InitialMigration') THEN
    CREATE INDEX "IX_Products_CategoryId" ON "Products" ("CategoryId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251107051528_InitialMigration') THEN
    CREATE INDEX "IX_SupportChats_AdminId" ON "SupportChats" ("AdminId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251107051528_InitialMigration') THEN
    CREATE INDEX "IX_SupportChats_CustomerId" ON "SupportChats" ("CustomerId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251107051528_InitialMigration') THEN
    CREATE INDEX "IX_SupportMessages_ChatId" ON "SupportMessages" ("ChatId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251107051528_InitialMigration') THEN
    CREATE INDEX "IX_SupportMessages_ReplyToMessageId" ON "SupportMessages" ("ReplyToMessageId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251107051528_InitialMigration') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251107051528_InitialMigration', '9.0.10');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251107161646_AddIsDeletedToEntitities') THEN
    ALTER TABLE "Products" ADD "IsDeleted" boolean NOT NULL DEFAULT FALSE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251107161646_AddIsDeletedToEntitities') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251107161646_AddIsDeletedToEntitities', '9.0.10');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251107162326_AddIsDeletedToProductLikes') THEN
    ALTER TABLE "ProductLikes" ADD "IsDeleted" boolean NOT NULL DEFAULT FALSE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251107162326_AddIsDeletedToProductLikes') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251107162326_AddIsDeletedToProductLikes', '9.0.10');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251215122648_UpdateDatabaseSchema') THEN
    ALTER TABLE "Customers" DROP COLUMN "Email";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251215122648_UpdateDatabaseSchema') THEN
    ALTER TABLE "Admins" DROP COLUMN "Email";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251215122648_UpdateDatabaseSchema') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251215122648_UpdateDatabaseSchema', '9.0.10');
    END IF;
END $EF$;
COMMIT;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM ""__EFMigrationsHistory"" WHERE ""MigrationId"" = '20260129_AddProductCategoriesTable') THEN
    -- Step 1: Create ProductCategories table
    CREATE TABLE ""ProductCategories"" (
        ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
        ""ProductId"" integer NOT NULL,
        ""CategoryId"" integer NOT NULL,
        ""CreatedAt"" text NOT NULL,
        ""UpdatedAt"" text,
        ""DeletedAt"" text,
        ""CreatedBy"" integer,
        ""UpdatedBy"" integer,
        ""DeletedBy"" integer,
        ""IsDeleted"" boolean NOT NULL DEFAULT FALSE,
        CONSTRAINT ""PK_ProductCategories"" PRIMARY KEY (""Id""),
        CONSTRAINT ""FK_ProductCategories_Products_ProductId"" FOREIGN KEY (""ProductId"") REFERENCES ""Products"" (""Id"") ON DELETE CASCADE,
        CONSTRAINT ""FK_ProductCategories_Categories_CategoryId"" FOREIGN KEY (""CategoryId"") REFERENCES ""Categories"" (""Id"") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM ""__EFMigrationsHistory"" WHERE ""MigrationId"" = '20260129_AddProductCategoriesTable') THEN
    CREATE INDEX ""IX_ProductCategories_ProductId"" ON ""ProductCategories"" (""ProductId"");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM ""__EFMigrationsHistory"" WHERE ""MigrationId"" = '20260129_AddProductCategoriesTable') THEN
    CREATE INDEX ""IX_ProductCategories_CategoryId"" ON ""ProductCategories"" (""CategoryId"");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM ""__EFMigrationsHistory"" WHERE ""MigrationId"" = '20260129_AddProductCategoriesTable') THEN
    INSERT INTO ""ProductCategories"" (""ProductId"", ""CategoryId"", ""CreatedAt"", ""IsDeleted"")
    SELECT 
        ""Id"" as ""ProductId"",
        ""CategoryId"",
        COALESCE(""CreatedAt"", NOW()::text) as ""CreatedAt"",
        FALSE as ""IsDeleted""
    FROM ""Products""
    WHERE ""CategoryId"" IS NOT NULL AND ""DeletedAt"" IS NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM ""__EFMigrationsHistory"" WHERE ""MigrationId"" = '20260129_AddProductCategoriesTable') THEN
    ALTER TABLE ""Products"" DROP CONSTRAINT IF EXISTS ""FK_Products_Categories_CategoryId"";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM ""__EFMigrationsHistory"" WHERE ""MigrationId"" = '20260129_AddProductCategoriesTable') THEN
    DROP INDEX IF EXISTS ""IX_Products_CategoryId"";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM ""__EFMigrationsHistory"" WHERE ""MigrationId"" = '20260129_AddProductCategoriesTable') THEN
    ALTER TABLE ""Products"" DROP COLUMN IF EXISTS ""CategoryId"";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM ""__EFMigrationsHistory"" WHERE ""MigrationId"" = '20260129_AddProductCategoriesTable') THEN
    INSERT INTO ""__EFMigrationsHistory"" (""MigrationId"", ""ProductVersion"")
    VALUES ('20260129_AddProductCategoriesTable', '9.0.10');
    END IF;
END $EF$;
