using System;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ZiyoMarket.Data.Migrations
{
    /// <inheritdoc />
    public partial class AddProductCategoriesTableV2 : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // Create ProductCategories table if it doesn't exist (Railway won't have it)
            migrationBuilder.Sql(@"
                CREATE TABLE IF NOT EXISTS ""ProductCategories"" (
                    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
                    ""ProductId"" integer NOT NULL,
                    ""CategoryId"" integer NOT NULL,
                    ""CreatedAt"" text NOT NULL,
                    ""UpdatedAt"" text,
                    ""DeletedAt"" text,
                    CONSTRAINT ""PK_ProductCategories"" PRIMARY KEY (""Id""),
                    CONSTRAINT ""FK_ProductCategories_Categories_CategoryId"" FOREIGN KEY (""CategoryId"") REFERENCES ""Categories"" (""Id"") ON DELETE CASCADE,
                    CONSTRAINT ""FK_ProductCategories_Products_ProductId"" FOREIGN KEY (""ProductId"") REFERENCES ""Products"" (""Id"") ON DELETE CASCADE
                );
            ");

            // Create indexes if not exist
            migrationBuilder.Sql(@"
                CREATE INDEX IF NOT EXISTS ""IX_ProductCategories_ProductId"" ON ""ProductCategories"" (""ProductId"");
                CREATE INDEX IF NOT EXISTS ""IX_ProductCategories_CategoryId"" ON ""ProductCategories"" (""CategoryId"");
            ");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(name: "ProductCategories");
        }
    }
}
